# Generated by Django 3.0.6 on 2020-05-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crew_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('experience', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('year_of_birth', models.DateField()),
                ('functions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='flight_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('cargo_weight', models.IntegerField()),
                ('number_of_people', models.IntegerField()),
                ('flight_duration', models.TimeField()),
                ('flight_cost', models.IntegerField()),
                ('special_flight', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='helicopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_helicopter', models.CharField(max_length=50)),
                ('production_date', models.DateField()),
                ('carrying', models.IntegerField()),
                ('date_of_last_repair', models.DateField()),
                ('time_resource_until_the_next_major_overhaul', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='helicopter_crew_identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment_of_crew_on_the_helicopter', models.DateField()),
                ('id_crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crew_member')),
                ('id_helicopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helicopter')),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment_of_the_pilot_on_the_helicopter', models.DateField()),
                ('id_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flight_information')),
                ('id_helicopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helicopter')),
            ],
        ),
    ]
