# Generated by Django 3.0.6 on 2020-06-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.RemoveField(
            model_name='flight_information',
            name='flight_cost',
        ),
        migrations.RemoveField(
            model_name='flight_information',
            name='special_flight',
        ),
    ]
