# Generated by Django 3.0.6 on 2020-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200606_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew_member',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helicopter',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
