# Generated by Django 3.0.6 on 2020-06-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200606_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment_of_the_pilot_on_the_helicopter', models.DateTimeField(auto_now_add=True)),
                ('id_crew_member_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fist', to='app.crew_member')),
                ('id_crew_member_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='app.crew_member')),
                ('id_crew_member_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='app.crew_member')),
                ('id_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flight_information')),
                ('id_helicopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helicopter')),
            ],
        ),
    ]
