# Generated by Django 3.0.6 on 2020-06-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200606_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id_crew_member_1',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='id_crew_member_2',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='id_crew_member_3',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='id_flight',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='id_helicopter',
        ),
        migrations.RemoveField(
            model_name='helicopter_crew_identification',
            name='id_crew_member',
        ),
        migrations.RemoveField(
            model_name='helicopter_crew_identification',
            name='id_helicopter',
        ),
    ]
