# Generated by Django 3.0.6 on 2020-06-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_flight_information_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id_crew_member',
        ),
        migrations.AddField(
            model_name='flight',
            name='id_crew_member1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crew_member1', to='app.crew_member'),
        ),
        migrations.AddField(
            model_name='flight',
            name='id_crew_member2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crew_member2', to='app.crew_member'),
        ),
        migrations.AddField(
            model_name='flight',
            name='id_crew_member3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crew_member3', to='app.crew_member'),
        ),
    ]
