# Generated by Django 3.0.6 on 2020-06-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200607_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='id_crew_member1',
            new_name='id_crew_member_1',
        ),
    ]
