# Generated by Django 3.0.6 on 2020-06-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200607_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id_crew_member2',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='id_crew_member3',
        ),
        migrations.AddField(
            model_name='flight',
            name='id_crew_member_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crew_member_2', to='app.crew_member'),
        ),
        migrations.AddField(
            model_name='flight',
            name='id_crew_member_3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crew_member_3', to='app.crew_member'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id_crew_member_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_member_1', to='app.crew_member'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flight_information'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id_helicopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helicopter'),
        ),
    ]
