# Generated by Django 3.0.6 on 2020-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200607_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew_member',
            name='id_flight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight_information',
            name='id_helicopter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
