version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=danceclasses
      - POSTGRES_USER=dell
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes:
      - ./dbs/postgres_data:/var/lib/postgresql/data/
  api:
    build: backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000";
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: frontend
    command: npm start;
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api